image:
  # We use the public proxysql repo and tag, because we don't want to expose our private ECR repo details because this is a public repo
  repository: proxysql/proxysql
  tag: "2.4.6" # must be in quotes
  pullPolicy: IfNotPresent

annotations:
  # key: value

initContainer:
  enabled: true
  image:
    repository: amazon/aws-cli
    tag: "2.13.4"
    pullPolicy: IfNotPresent

appName: "my-app"
proxysql_role: primary
environment: development
use_aws_aurora: false # this variable is used to configure feature flag for proxysql to use AWS Aurora

# -- Environment variables to be passed to the app container
env:
# - name: ENVIRONMENT
#   value: "dev"

serviceAccount:
  enabled: true
  annotations:
    # key: value

resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 50m
    memory: 128Mi

probes:
  startupProbe:
    failureThreshold: 10
    periodSeconds: 3
    httpGet:
      path: /metrics
      port: metrics
  livenessProbe:
    failureThreshold: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3
    initialDelaySeconds: 10
    httpGet:
      path: /metrics
      port: metrics
