image:
  repository: 768383028426.dkr.ecr.eu-central-1.amazonaws.com/pawapay-proxysql
  tag: "2023_01_05_17_46_26" # must be in quotes
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 256Mi
