image:
  repository: proxysql/proxysql
  tag: "2.4.6" # must be in quotes
  pullPolicy: IfNotPresent

initContainer:
  enabled: true
  image:
    repository: amazon/aws-cli
    tag: "2.13.4"
    pullPolicy: IfNotPresent

appName: "my-app"
proxysql_role: primary
environment: development

serviceAccount:
  enabled: false

resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 50m
    memory: 256Mi
