apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  {{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "proxysql.labels" $ | nindent 4 }}
spec:
  ports:
    - name: proxysql
      protocol: TCP
      port: 6033
      targetPort: proxysql
    - name: admin
      protocol: TCP
      port: 6032
      targetPort: admin
    - name: metrics
      protocol: TCP
      port: 6070
      targetPort: metrics
  selector:
    {{- include "proxysql.selectorLabels" . | nindent 4 }}
