apiVersion: v1
kind: Service
metadata:
  name: {{ template "activemq.fullname" . }}
  labels: {{ include "activemq.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4}}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: {{ template "activemq.fullname" . }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml . | indent 4 }}
{{- end }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}